# Generated by Django 2.1 on 2019-12-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_complain_table_house_holding_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain_table',
            name='image',
            field=models.ImageField(default='webapp/images/icon.png', upload_to='images/'),
        ),
    ]
