# Generated by Django 2.1 on 2019-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_complain_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain_table',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
