# Generated by Django 2.1 on 2019-12-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191208_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain_table',
            name='image',
            field=models.ImageField(default='webapp/images/icon.png', upload_to='images/'),
        ),
    ]
