# Generated by Django 2.1 on 2019-12-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191208_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain_table',
            old_name='image',
            new_name='image_field',
        ),
    ]
