# Generated by Django 2.1 on 2019-12-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20191208_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='dateshow',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
