# Generated by Django 2.1 on 2019-12-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_notice_dateshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain_table',
            name='dateshow',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='complain_table',
            name='timeshow',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
